### ISSUE TITLE
example train data in english

### ISSUE THREAD

**Issue by pantchox** [LeeXun/word2vector#5]
Hi, 

Great work!

I would like to test this with english train data, but the train data file structure you have is not in english so i don't know how to structure my text - mostly twitter tweets.

thanks!

**Comment by LeeXun** [comment]
Hi Pantchox,

Please just seperate the words by space in the data file. Because in Chinese, we don't use space as a seperator of  words. So we need to use some other tools to create our data file. However in English, every words have already been seperate by spaces. Like [this file](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit) from google news.

**Comment by pantchox** [comment]
thank you for your quick response, the file you  provided is a binary file which is already trained if i am not mistaken.

so if i would like to make a train file it can be just like this:
```
this is my first tweet #firsttime
this is another tweet made by different user who love eating #cake
....
```

just having this structure is enough for training to create the bin file? that is my question

**Comment by LeeXun** [comment]
Should put all the words in the same line, without comments, and remove all stop words. In English, probably need to use word2phrase for data pre-formatting. For example, my name lee xun is two words, but it should be consider as one word in word2vector, so it should be parsed into leexun. (Note the space in the seperator)

**Comment by pantchox** [comment]
Thanks!
